--
output:
  html_document:
    theme: readable
    toc: yes
---
```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
options(scipen=1, digits=4, width=80)
library(faraway)
library(readr)
```
# CS 498 AML Homework 4
## Question 7.10
```{r, message=FALSE}
physical <- read_csv("./q2.csv")
```
**(a)**
```{r}
model1 <- lm(Mass ~ 1 + Fore + Bicep + Chest + Neck + Shoulder + Waist + Height + Calf + Thigh + Head, data=physical)
scale = c(min(model1$residuals), max(model1$residuals))
summary(model1)
plot(model1$fitted, model1$residuals, main="Residuls vs Fitted", sub="original data", xlab="Fitted values", ylab="Residuals")
```
**(b)**
From the residuals vs fitted graph, the errors seem to be about normally shaped with a mean of 0. 
```{r}
model2 <- lm((Mass)^(1/3) ~ 1 + Fore + Bicep + Chest + Neck + Shoulder + Waist + Height + Calf + Thigh + Head, data=physical)
par(mfrow=c(1,1))
summary(model2)
plot(model2$fitted, model2$residuals, main="Residuls vs Fitted", sub="transformed data", xlab="Fitted values", ylab="Residuals")
plot(model2$fitted, model2$residuals, main="Residuls vs Fitted", sub="transformed data, original scale", xlab="Fitted values", ylab="Residuals", ylim=scale)
```

**(c)**

The residuals of the transformed model but on the scale of the orignal model, are really close to 0. Therefore the transformed model is clearly better.