#! env python

folder_path = "./cifar-10-batches-py/"
def unpickel(file):
    import cPickle
    fo = open(file, 'rb')
    dict = cPickle.load(fo)
    fo.close()
    return dict

data = unpickel(folder_path + "data_batch_1")

print data

