---
output:
  html_document:
    theme: readable
    toc: yes
---
```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
options(scipen=1, digits=4, width=80)
library(faraway)
library(readr)
library(caret)
library(klaR)
library(lattice)
library(glmnet)
library(plotmo)
library(gridExtra)
```

# CS 498 AML Homework 5
## Question 1 - Music
```{r, message=FALSE}
music <- read_csv('./music.csv')
num_features = dim(music)[2]-2
music["latitude"] <- music["latitude"] + 90
music["longitude"] <- music["longitude"] + 180
```


### Latitude
**(a)** Fit a linear model

```{r}
lat.lm <- lm(latitude ~ . - longitude, data = music)
```

```{r, echo=FALSE}
print(c("The R^2 value is", summary(lat.lm)$r.squared))
par(mfrow=c(2,2))
plot(lat.lm)
```

**(b)** Box-Cox

```{r}
lat.bc_info = boxcox(lat.lm, lambda=seq(-1,5))
lat.bc_lambda = lat.bc_info$x[which.max(lat.bc_info$y)]
lat.lm_lambda = lm( (latitude^lat.bc_lambda-1)/lat.bc_lambda ~ . - longitude, data=music)
```

```{r, echo=FALSE}
par(mfrow=c(2,2))
plot(lat.lm_lambda)
```

```{r, echo=FALSE}
print(c("The new R^2 value is", summary(lat.lm_lambda)$r.squared))
print(c("The Box-Cox optimal lambda is", lat.bc_lambda))
```

**(c)** Regularization
```{r}
# Lasso L1
lat.l1 = glmnet(as.matrix(music[1:num_features]),
				as.matrix(music["latitude"]^lat.bc_lambda),
				alpha=1)
lat.l1_cv = cv.glmnet(as.matrix(music[1:num_features]),
				as.matrix(music["latitude"]^lat.bc_lambda),
				alpha=1)
```

```{r, echo=FALSE}
par(mfrow=c(1,2))
plot(lat.l1, xvar="lambda")
plot(lat.l1_cv)
```


```{r}
# Ridge L2
lat.l2 = glmnet(as.matrix(music[1:num_features]),
				as.matrix(music["latitude"]^lat.bc_lambda),
				alpha=0)
lat.l2_cv = cv.glmnet(as.matrix(music[1:num_features]),
				as.matrix(music["latitude"]^lat.bc_lambda),
				alpha=0)
```

```{r, echo=FALSE}
par(mfrow=c(1,2))
plot(lat.l2, xvar="lambda")
plot(lat.l2_cv)
```


### Longitude
**(a)** Fit a linear model
```{r}
lon.lm <- lm(longitude ~ . - latitude, data = music)
```

```{r, echo=FALSE}
print(c("The R^2 value is", summary(lon.lm)$r.squared))
par(mfrow=c(2,2))
plot(lon.lm)
```

**(b)** Box-Cox

```{r}
lon.bc_info = boxcox(lon.lm)
lon.bc_lambda = lon.bc_info$x[which.max(lon.bc_info$y)]
lon.lm_lambda = lm((longitude^lon.bc_lambda-1)/lon.bc_lambda ~ . - latitude, data=music)
```

```{r, echo=FALSE}
print(c("The new R^2 value is", summary(lon.lm_lambda)$r.squared))
print(c("The Box-Cox optimal lambda is", lon.bc_lambda))
par(mfrow=c(2,2))
plot(lon.lm)
```

The Box-Cox transformation does not help becuase the residuals are not really effected. Since the optimal $\lambda$ found by Box-Cox is about $1$, we don't expect this to do a lot.

**(c)** Regularization
```{r}
# Lasso L1
lon.l1 = glmnet(as.matrix(music[1:num_features]),
				as.matrix(music["longitude"]^lon.bc_lambda),
				alpha=1)
lon.l1_cv = cv.glmnet(as.matrix(music[1:num_features]),
				as.matrix(music["longitude"]^lon.bc_lambda),
				alpha=1)
```

```{r, echo=FALSE}
par(mfrow=c(1,2))
plot(lon.l1, xvar="lambda")
plot(lon.l1_cv)
```

```{r}
# Ridge L2
lon.l2 = glmnet(as.matrix(music[1:num_features]),
				as.matrix(music["longitude"]^lon.bc_lambda),
				alpha=0)
lon.l2_cv = cv.glmnet(as.matrix(music[1:num_features]),
				as.matrix(music["longitude"]^lon.bc_lambda),
				alpha=0)
```

```{r, echo=FALSE}
par(mfrow=c(1,2))
plot(lon.l2, xvar="lambda")
plot(lon.l2_cv)
```



## Question 2 - Taiwan

## Question 3 - Cancer
